baseURL = "/"
publishdir = "public/dev-guide"
languageCode = "zh-cn"
defaultContentLanguage = "zh"
staticDir = "static/dev-guide"
title = "KubeSphere Development Guide"
theme = "hugo-theme-learn"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  description = "A set of development guidelines for KubeSphere developers."
  author = "KubeSphere"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  disableInlineCopyToClipBoard = true
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = "::"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
editURL = "https://github.com/kubesphere/dev-guide/edit/master/sites/dev-guide/content/en/"
contentDir = "sites/dev-guide/content/en"
title = "KubeSphere Development Guide"
weight = 1
languageName = "English"
landingPageURL = ""

[Languages.zh]
editURL = "https://github.com/kubesphere/dev-guide/edit/master/sites/dev-guide/content/zh/"
contentDir = "sites/dev-guide/content/zh"
title = "KubeSphere 开发指南"
weight = 3
languageName = "简体中文"
landingPageURL = ""
